### ISSUE TITLE
ngrok instructions in README twice

### ISSUE THREAD

**Issue by jarodreyes** [TwilioDevEd/warm-transfer-rails#3]
Need to remove one of the ngrok instructions in the README

**Comment by mcelicalderon** [comment]
@jarodreyes We make a reference from one of the steps to this section of the readme about exposing your app to the wider internet. This section contains more detail and a link to a blogpost on how to use ngrok. If you think it would be better, we can join all this information in one of the steps.

**Comment by nebtrx** [comment]
Yes, we usually refers to [this blog post](https://www.twilio.com/blog/2013/10/test-your-webhooks-locally-with-ngrok.html) or refer a forward more explanatory section inside the md file as @atbaker suggest us in the past

**Comment by jarodreyes** [comment]
Let's simplify the instructions here and only mention it once.
