### ISSUE TITLE
Weird indentation throughout the app

### ISSUE THREAD

**Issue by jarodreyes** [TwilioDevEd/warm-transfer-rails#4]
Please do not do:
```ruby
TwimlGenerator
      .generate_connect_conference(params[:conference_id], AGENT_WAIT_URL, true, false)
```
Instead use oneline: `TwimlGenerator.generate_connect_conference(params[:conference_id], AGENT_WAIT_URL, true, false)`

**Comment by mcelicalderon** [comment]
@jarodreyes Please take a looks at the latest commit. I changed the style of multi-line statements.

**Comment by jarodreyes** [comment]
:+1:
