### ISSUE TITLE
Need instructions on how to demo. Also special notes about client support.

### ISSUE THREAD

**Issue by jarodreyes** [TwilioDevEd/warm-transfer-rails#5]
Need to add a section to the README:

## How to Demo:
* In two separate browser windows navigate to https:// <hghgh>.ngrok.io/
* Connect as agent1 and agent2
* Dial Twilio Number
...etc

Also need to note some limitations of Client.
* Need to use a secure ngrok endpoint for CLient so use https://
* Can not use Safari, only latest WebRTC is supported (Chrome ideal)
* Need to connect as both Agents before you call the line.

**Comment by mcelicalderon** [comment]
Sure, we can add this.
